### ISSUE TITLE
Non-continuous suffixes

### ISSUE THREAD

**Issue by MBtech** [teracow/googliser#41]
If I understand correctly, if the script fails to download an image, the integer suffix that would have been allocated to that image file is skipped. So in the end image names have suffixes that aren't continuous.

Does that serve a particular purpose? 
Wouldn't it be better if the suffixes are continuous? So that it's easier to loop through the resulting image files.

**Comment by teracow** [comment]
It's due to the way URLs are managed via googliser and ensures each of the (potentially hundreds of) forked image download functions does not need to know anything other than the URL it has to attempt to download, and the index of that URL from the links file. 

So, each indexed filename has a 1:1 relationship with the URL list googliser reads from (the first link in the links file is the first image tried). This makes it quite easy to locate an original URL for any downloaded image. 

Iterating through a loop of non-contiguous filename indexes is a fairly trivial matter in contrast to refactoring googliser's code to ensure the filenames are contiguous. ;)

**Comment by MBtech** [comment]
Ahh fair enough. Maintaining continuous indexes with parallel fetching would be an unnecessary pain.

**Comment by teracow** [comment]
Just thinking out-loud, rather than rewrite the existing code, it would be fairly simple to offer another option like `--reindex-rename` that - if specified - operates as a post-downloading routine and renames all  downloaded images into a contiguous order. Thoughts?
